/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SelecionarCanalController;
import Factory.ConnectionFactory;
import Helper.ConfiguracoesAtivasHelper;
import Helper.LoginHelper;
import Helper.SelecionarCanalHelper;
import Model.Canais;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Frame;

/**
 *
 * @author nicol
 */
public class SelecionarCanal extends javax.swing.JFrame {

    private final SelecionarCanalController controller;
    Connection con = new ConnectionFactory().getConnection();
    PreparedStatement stmt = null;
    ResultSet rs = null;
    
    public SelecionarCanal() {
        initComponents();
        controller = new SelecionarCanalController(this);
        this.controller.restaurarDadosCombobox();
    }
    
    public void acessarConfiguracoesCanais() throws SQLException{  
        String sql = "SELECT * FROM canais WHERE nome_canal = ?";
        
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, (String) selecionarCanal.getSelectedItem());

            rs = stmt.executeQuery();
            
            if (rs.next()){
                Dimension telaAtual = getPreferredSize();
                Dimension telaNova = getSize();
                SelecionarCanalHelper selecionarCanalHelper = new SelecionarCanalHelper();
                String select = (String) getSelecionarCanal().getSelectedItem();
                
                String padraoAutenticacao = rs.getString(4);
                Canais canal = new Canais();
                canal.setCanal((String) selecionarCanal.getSelectedItem());
                
                int tamanhoTelaAtual = (int) telaAtual.getWidth();
                int tamanhoTelaNova = (int) telaNova.getWidth();
                
                if (padraoAutenticacao.equals("Token")) {
                    SelecionarCanalController selecionarCanalController = new SelecionarCanalController(this);
                    selecionarCanalController.acessarConfiguracoesCanaisToken();
                    this.dispose();
                } 
                
                else {
                    if (tamanhoTelaAtual < tamanhoTelaNova) {
                        selecionarCanalHelper.setUser(getMinhaConta().getText());
                        selecionarCanalHelper.setItemSelect(select);
                        
                        ConfiguracoesCanaisUsuarioSenha configuracoesCanaisUsuarioSenha = new ConfiguracoesCanaisUsuarioSenha();
                        configuracoesCanaisUsuarioSenha.setExtendedState(Frame.MAXIMIZED_BOTH);
                        configuracoesCanaisUsuarioSenha.exportar(selecionarCanalHelper);
                        configuracoesCanaisUsuarioSenha.exportar2(selecionarCanalHelper);
                        configuracoesCanaisUsuarioSenha.setVisible(true);
                        this.dispose(); 
                    }
                    
                    else {
                        selecionarCanalHelper.setUser(getMinhaConta().getText());
                        selecionarCanalHelper.setItemSelect(select);
                        
                        ConfiguracoesCanaisUsuarioSenha configuracoesCanaisUsuarioSenha = new ConfiguracoesCanaisUsuarioSenha();
                        configuracoesCanaisUsuarioSenha.exportar(selecionarCanalHelper);
                        configuracoesCanaisUsuarioSenha.exportar2(selecionarCanalHelper);
                        configuracoesCanaisUsuarioSenha.setVisible(true);
                        this.dispose(); 
                    }
                }
            } 
            
            else {
                
                JOptionPane.showMessageDialog(null, "Selecione um canal");
            }
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Erro :");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        minhaConta = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        configAtivas = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        selecionarCanal = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        continuarButtonSelecionarCanal = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleção de Canais");
        setMaximumSize(new java.awt.Dimension(1100, 580));
        setMinimumSize(new java.awt.Dimension(1100, 580));
        setPreferredSize(new java.awt.Dimension(1100, 580));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 62, 21));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(45, 18, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(920, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/logo.png"))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(260, 30));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        minhaConta.setBackground(new java.awt.Color(255, 255, 255));
        minhaConta.setFont(new java.awt.Font("Inter", 1, 22)); // NOI18N
        minhaConta.setText("ADMIN");
        minhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minhaContaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 72);
        jPanel12.add(minhaConta, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/logged.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -38;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel12.add(jLabel7, gridBagConstraints);

        configAtivas.setBackground(new java.awt.Color(45, 18, 75));
        configAtivas.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        configAtivas.setForeground(new java.awt.Color(255, 255, 255));
        configAtivas.setText("CANAIS ATIVOS");
        configAtivas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configAtivasMouseClicked(evt);
            }
        });
        configAtivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configAtivasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(configAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(1033, 60));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel10.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(1033, 130));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        selecionarCanal.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        selecionarCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o canal que deseja registrar" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 371, 29, 363);
        jPanel8.add(selecionarCanal, gridBagConstraints);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        continuarButtonSelecionarCanal.setBackground(new java.awt.Color(252, 121, 0));
        continuarButtonSelecionarCanal.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        continuarButtonSelecionarCanal.setForeground(new java.awt.Color(255, 255, 255));
        continuarButtonSelecionarCanal.setText("CONTINUAR");
        continuarButtonSelecionarCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonSelecionarCanalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 132, 29, 366);
        jPanel9.add(continuarButtonSelecionarCanal, gridBagConstraints);

        sairButton.setBackground(new java.awt.Color(255, 0, 0));
        sairButton.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("SAIR");
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairButtonMouseClicked(evt);
            }
        });
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 378, 29, 0);
        jPanel9.add(sairButton, gridBagConstraints);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continuarButtonSelecionarCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonSelecionarCanalActionPerformed
        try {
            acessarConfiguracoesCanais();
        } catch (SQLException ex) {
            Logger.getLogger(SelecionarCanal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_continuarButtonSelecionarCanalActionPerformed

    private void minhaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minhaContaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_minhaContaMouseClicked

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairButtonActionPerformed

    private void sairButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseClicked
        this.controller.sairUser();
    }//GEN-LAST:event_sairButtonMouseClicked

    private void configAtivasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configAtivasMouseClicked
        this.controller.acessarConfigUsuario();
    }//GEN-LAST:event_configAtivasMouseClicked

    private void configAtivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configAtivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configAtivasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarCanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarCanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarCanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarCanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarCanal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configAtivas;
    private javax.swing.JButton continuarButtonSelecionarCanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel minhaConta;
    private javax.swing.JButton sairButton;
    private javax.swing.JComboBox<String> selecionarCanal;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getSelecionarCanal() {
        return selecionarCanal;
    }

    public void setSelecionarCanal(JComboBox<String> selecionarCanal) {
        this.selecionarCanal = selecionarCanal;
    }

    public JLabel getMinhaConta() {
        return minhaConta;
    }

    public void setMinhaConta(JLabel minhaConta) {
        this.minhaConta = minhaConta;
    }
    
    
    //EXPORTAÇÕES
    public void exportar(LoginHelper loginHelper) {
        minhaConta.setText(loginHelper.getUser());
    }
    
    public void exportar2(ConfiguracoesAtivasHelper configuracoesAtivasHelper) {
        minhaConta.setText(configuracoesAtivasHelper.getUser());
    }

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
}
