/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroController;

/**
 *
 * @author nicol
 */
public class Cadastro extends javax.swing.JFrame {

    private final CadastroController controller;
    
    
    /**
     * Creates new form Login
     */
    public Cadastro() {
        initComponents();
        controller = new CadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmaSenhaCadastro = new javax.swing.JPasswordField();
        SenhaCadastro = new javax.swing.JPasswordField();
        SetaVoltarCadastro = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        EmailCadastro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UsuarioCadastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NomeCompletoCadastro = new javax.swing.JTextField();
        CadastraSeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ConfirmaSenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 260, 50));
        getContentPane().add(SenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 260, 50));

        SetaVoltarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/arrow.png"))); // NOI18N
        SetaVoltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetaVoltarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(SetaVoltarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 60));

        jLabel12.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("E-mail:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 180, -1));

        EmailCadastro.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        EmailCadastro.setForeground(new java.awt.Color(0, 0, 0));
        EmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(EmailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 260, 50));

        jLabel11.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Confirme a senha:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 180, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Senha:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 180, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuário:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 180, -1));

        UsuarioCadastro.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        UsuarioCadastro.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 260, 50));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nome Completo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 180, -1));

        NomeCompletoCadastro.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        NomeCompletoCadastro.setForeground(new java.awt.Color(0, 0, 0));
        NomeCompletoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCompletoCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(NomeCompletoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 260, 50));

        CadastraSeButton.setBackground(new java.awt.Color(252, 121, 0));
        CadastraSeButton.setFont(new java.awt.Font("Inter", 1, 25)); // NOI18N
        CadastraSeButton.setForeground(new java.awt.Color(255, 255, 255));
        CadastraSeButton.setText("CADASTRE-SE");
        CadastraSeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraSeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CadastraSeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 210, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/logo.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setName(""); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 280, 80));

        jLabel3.setBackground(new java.awt.Color(45, 18, 75));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 30));

        jLabel2.setBackground(new java.awt.Color(255, 62, 21));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 950, 590));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nome Completo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 180, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastraSeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraSeButtonActionPerformed
        this.controller.navegarConfirmacaoCadastro();
    }//GEN-LAST:event_CadastraSeButtonActionPerformed

    private void NomeCompletoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCompletoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCompletoCadastroActionPerformed

    private void UsuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioCadastroActionPerformed

    private void EmailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailCadastroActionPerformed

    private void SetaVoltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetaVoltarCadastroActionPerformed
        this.controller.navegarDeVoltaProLogin();
    }//GEN-LAST:event_SetaVoltarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastraSeButton;
    private javax.swing.JPasswordField ConfirmaSenhaCadastro;
    private javax.swing.JTextField EmailCadastro;
    private javax.swing.JTextField NomeCompletoCadastro;
    private javax.swing.JPasswordField SenhaCadastro;
    private javax.swing.JButton SetaVoltarCadastro;
    private javax.swing.JTextField UsuarioCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
