/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author nicol
 */
public class ConfiguracoesDeCanaisToken extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ConfiguracoesDeCanaisToken() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarButtonToken = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CadastroToken = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CadastroIdContaToken = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CadastroCanalToken = new javax.swing.JTextField();
        SalvarButtonToken = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações de Canais");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VoltarButtonToken.setBackground(new java.awt.Color(45, 18, 75));
        VoltarButtonToken.setFont(new java.awt.Font("Inter", 1, 25)); // NOI18N
        VoltarButtonToken.setForeground(new java.awt.Color(255, 255, 255));
        VoltarButtonToken.setText("VOLTAR");
        VoltarButtonToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonTokenActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarButtonToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 150, 50));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Configurações de Canais");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 400, 50));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Token:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 180, -1));

        CadastroToken.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        CadastroToken.setForeground(new java.awt.Color(0, 0, 0));
        CadastroToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroTokenActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 260, 50));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID da conta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 180, -1));

        CadastroIdContaToken.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        CadastroIdContaToken.setForeground(new java.awt.Color(0, 0, 0));
        CadastroIdContaToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroIdContaTokenActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroIdContaToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 260, 50));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Canal:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 60, 20));

        CadastroCanalToken.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        CadastroCanalToken.setForeground(new java.awt.Color(0, 0, 0));
        CadastroCanalToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCanalTokenActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroCanalToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 260, 50));

        SalvarButtonToken.setBackground(new java.awt.Color(252, 121, 0));
        SalvarButtonToken.setFont(new java.awt.Font("Inter", 1, 25)); // NOI18N
        SalvarButtonToken.setForeground(new java.awt.Color(255, 255, 255));
        SalvarButtonToken.setText("SALVAR");
        SalvarButtonToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonTokenActionPerformed(evt);
            }
        });
        getContentPane().add(SalvarButtonToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 150, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/logo.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setName(""); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, 80));

        jLabel3.setBackground(new java.awt.Color(45, 18, 75));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 30));

        jLabel2.setBackground(new java.awt.Color(255, 62, 21));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nome Completo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 180, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarButtonTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarButtonTokenActionPerformed

    private void CadastroCanalTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCanalTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroCanalTokenActionPerformed

    private void CadastroIdContaTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroIdContaTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroIdContaTokenActionPerformed

    private void CadastroTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroTokenActionPerformed

    private void VoltarButtonTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarButtonTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesDeCanaisToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesDeCanaisToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesDeCanaisToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesDeCanaisToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracoesDeCanaisToken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadastroCanalToken;
    private javax.swing.JTextField CadastroIdContaToken;
    private javax.swing.JTextField CadastroToken;
    private javax.swing.JButton SalvarButtonToken;
    private javax.swing.JButton VoltarButtonToken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
