package View;

import Controller.LoginPrincipalController;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author nicol
 */
public class LoginPrincipal extends javax.swing.JFrame {

    private final LoginPrincipalController controller;

    /**
     * Creates new form CadastroPrincipal
     */
    public LoginPrincipal() {
        initComponents();
        controller = new LoginPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        UsuarioButton = new javax.swing.JButton();
        OperadorButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setFocusableWindowState(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 75, 25));
        jLabel5.setText("BEM-VINDO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 250, 50));

        UsuarioButton.setBackground(new java.awt.Color(102, 102, 102));
        UsuarioButton.setFont(new java.awt.Font("Inter", 1, 25)); // NOI18N
        UsuarioButton.setForeground(new java.awt.Color(45, 18, 75));
        UsuarioButton.setText("USUÁRIO");
        UsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 170, 70));

        OperadorButton.setBackground(new java.awt.Color(102, 102, 102));
        OperadorButton.setFont(new java.awt.Font("Inter", 1, 25)); // NOI18N
        OperadorButton.setForeground(new java.awt.Color(45, 18, 75));
        OperadorButton.setText("OPERADOR");
        OperadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OperadorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/logo.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setName(""); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 280, 80));

        jLabel3.setBackground(new java.awt.Color(45, 18, 75));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 30));

        jLabel2.setBackground(new java.awt.Color(255, 62, 21));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 950, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OperadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorButtonActionPerformed
        this.controller.entrarNoLogin();
    }//GEN-LAST:event_OperadorButtonActionPerformed

    private void UsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioButtonActionPerformed
        this.controller.entrarNoLogin();
    }//GEN-LAST:event_UsuarioButtonActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OperadorButton;
    private javax.swing.JButton UsuarioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}