/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Factory.ConnectionFactory;
import Helper.SelecionarCanalHelper;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTextField;
import java.sql.SQLException;

/**
 *
 * @author nicol
 */
public class EditarUsuario extends javax.swing.JFrame {


    Connection con = new ConnectionFactory().getConnection();
    PreparedStatement stmt = null;
    ResultSet rs = null;
    
    public EditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salvarButton = new javax.swing.JButton();
        editUser = new javax.swing.JTextField();
        editRegistroUser = new javax.swing.JTextField();
        editIDContaUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editCanalUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editPassUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar");
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(1365, 767));
        setMinimumSize(new java.awt.Dimension(850, 530));
        setPreferredSize(new java.awt.Dimension(890, 700));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 62, 21));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(45, 18, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(920, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setToolTipText("");
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(920, 60));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel2.setText("EDITE O CANAL:");
        jPanel7.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(1350, 300));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel3.setText("Canal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 231, 0, 0);
        jPanel8.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel4.setText("Usuário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 231, 0, 0);
        jPanel8.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel5.setText("Id da conta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 231, 0, 0);
        jPanel8.add(jLabel5, gridBagConstraints);

        salvarButton.setBackground(new java.awt.Color(252, 121, 0));
        salvarButton.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        salvarButton.setForeground(new java.awt.Color(255, 255, 255));
        salvarButton.setText("SALVAR");
        salvarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarButtonMouseClicked(evt);
            }
        });
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 164, 6, 403);
        jPanel8.add(salvarButton, gridBagConstraints);

        editUser.setBackground(new java.awt.Color(217, 217, 217));
        editUser.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        editUser.setAutoscrolls(false);
        editUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editUserKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 368;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 231, 0, 0);
        jPanel8.add(editUser, gridBagConstraints);

        editRegistroUser.setBackground(new java.awt.Color(217, 217, 217));
        editRegistroUser.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        editRegistroUser.setAutoscrolls(false);
        editRegistroUser.setEnabled(false);
        editRegistroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRegistroUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 368;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 231, 0, 0);
        jPanel8.add(editRegistroUser, gridBagConstraints);

        editIDContaUser.setBackground(new java.awt.Color(217, 217, 217));
        editIDContaUser.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        editIDContaUser.setAutoscrolls(false);
        editIDContaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editIDContaUserKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 368;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 231, 0, 0);
        jPanel8.add(editIDContaUser, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel6.setText("Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 231, 0, 0);
        jPanel8.add(jLabel6, gridBagConstraints);

        editCanalUser.setBackground(new java.awt.Color(217, 217, 217));
        editCanalUser.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        editCanalUser.setAutoscrolls(false);
        editCanalUser.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 368;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 231, 0, 0);
        jPanel8.add(editCanalUser, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel7.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 231, 0, 0);
        jPanel8.add(jLabel7, gridBagConstraints);

        editPassUser.setBackground(new java.awt.Color(217, 217, 217));
        editPassUser.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        editPassUser.setAutoscrolls(false);
        editPassUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editPassUserKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 368;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 231, 6, 0);
        jPanel8.add(editPassUser, gridBagConstraints);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed

    }//GEN-LAST:event_salvarButtonActionPerformed

    private void salvarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButtonMouseClicked
        String sql = "UPDATE configuracao_canais_usuario SET nome_canal_usuario=?, id_conta_usuario=?, usuario_canal=?, senha_canal=? WHERE id_canal_usuario=?;";
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, editCanalUser.getText());
            stmt.setString(2, editIDContaUser.getText());
            stmt.setString(3, editUser.getText());
            stmt.setString(4, editPassUser.getText());
            stmt.setString(5, editRegistroUser.getText());
            
            stmt.executeUpdate();
            stmt.close();
            con.close();
            
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        this.dispose();
    }//GEN-LAST:event_salvarButtonMouseClicked

    private void editRegistroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRegistroUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editRegistroUserActionPerformed

    private void editIDContaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editIDContaUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String sql = "UPDATE configuracao_canais_usuario SET nome_canal_usuario=?, id_conta_usuario=?, usuario_canal=?, senha_canal=? WHERE id_canal_usuario=?;";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, editCanalUser.getText());
                stmt.setString(2, editIDContaUser.getText());
                stmt.setString(3, editUser.getText());
                stmt.setString(4, editPassUser.getText());
                stmt.setString(5, editRegistroUser.getText());

                stmt.executeUpdate();
                stmt.close();
                con.close();


            } catch (SQLException e) {
                System.out.println(e);
            }
            this.dispose();
        }
    }//GEN-LAST:event_editIDContaUserKeyPressed

    private void editUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editUserKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String sql = "UPDATE configuracao_canais_usuario SET nome_canal_usuario=?, id_conta_usuario=?, usuario_canal=?, senha_canal=? WHERE id_canal_usuario=?;";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, editCanalUser.getText());
                stmt.setString(2, editIDContaUser.getText());
                stmt.setString(3, editUser.getText());
                stmt.setString(4, editPassUser.getText());
                stmt.setString(5, editRegistroUser.getText());

                stmt.executeUpdate();
                stmt.close();
                con.close();


            } catch (SQLException e) {
                System.out.println(e);
            }
            this.dispose();
        }
    }//GEN-LAST:event_editUserKeyPressed

    private void editPassUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPassUserKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String sql = "UPDATE configuracao_canais_usuario SET nome_canal_usuario=?, id_conta_usuario=?, usuario_canal=?, senha_canal=? WHERE id_canal_usuario=?;";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, editCanalUser.getText());
                stmt.setString(2, editIDContaUser.getText());
                stmt.setString(3, editUser.getText());
                stmt.setString(4, editPassUser.getText());
                stmt.setString(5, editRegistroUser.getText());

                stmt.executeUpdate();
                stmt.close();
                con.close();


            } catch (SQLException e) {
                System.out.println(e);
            }
            this.dispose();
        }
    }//GEN-LAST:event_editPassUserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editCanalUser;
    private javax.swing.JTextField editIDContaUser;
    private javax.swing.JTextField editPassUser;
    private javax.swing.JTextField editRegistroUser;
    private javax.swing.JTextField editUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables

    public JTextField getEditCanal() {
        return editCanalUser;
    }

    public void setEditCanal(JTextField editCanal) {
        this.editCanalUser = editCanal;
    }

    public JTextField getEditIDConta() {
        return editIDContaUser;
    }

    public void setEditIDConta(JTextField editIDConta) {
        this.editIDContaUser = editIDConta;
    }

    public JTextField getEditRegistro() {
        return editRegistroUser;
    }

    public void setEditRegistro(JTextField editRegistro) {
        this.editRegistroUser = editRegistro;
    }

    public JTextField getEditTokenAlt() {
        return editUser;
    }

    public void setEditTokenAlt(JTextField editTokenAlt) {
        this.editUser = editTokenAlt;
    }

    public JTextField getEditTokenAlt1() {
        return editPassUser;
    }

    public void setEditTokenAlt1(JTextField editTokenAlt1) {
        this.editPassUser = editTokenAlt1;
    }

    
    
    
}
